micronaut:
  application:
    name: ssoExample
  security:
    authentication: idtoken
    oauth2:
      clients:
        okta:
          client-secret: '${OAUTH_CLIENT_SECRET:yyy}'
          client-id: '${OAUTH_CLIENT_ID:xxx}'
          openid:
            issuer: '${OIDC_ISSUER_DOMAIN:`https://dev-XXXXX.oktapreview.com`}/oauth2/${OIDC_ISSUER_AUTHSERVERID:default}'
    endpoints:
      logout:
        get-allowed: true